version: "3"
services:
  mysql:
    # Após a inicialização do container executar o comando abaixo
    # docker exec -i mysql sh -c 'exec mysql -u root -p"$MYSQL_ROOT_PASSWORD" < /mnt/app/script-mysql.sql'
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./api/_volumes/mysql/data:/var/lib/mysql
      - ./api/_volumes/mysql/conf.d:/etc/mysql/conf.d
      - ./api/_volumes/scripts:/mnt/app
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  node-server:
    depends_on:
      - mysql
    image: node
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    command: "npm start"
    ports:
      - "8000:8000"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672